AWSTemplateFormatVersion: '2010-09-09'
Description: 'Aurora clone manager example'
Parameters:
  SourceClusterId:
    Type: String
    Description: "The ID of the root cluster"
  CopyCreatedSince:
    Type: String
    Description: "To be eligible for cloning, a copy must have been created after this time"
    Default: 1970-01-01T00:00:00.000Z
  CloneManagerStack:
    Type: String
    Description: "The name of the stack defining the Aurora clone manager"
    Default: "aurora-clone-manager"
  AccessPrincipal:
    Type: String
    Description: "The principal to grant access to the key, see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#Principal_specifying"
    Default: "*"
Resources:
  SecretKMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable access by the clone manager
            Effect: Allow
            Principal:
              AWS:
                Fn::ImportValue:
                  !Sub "${CloneManagerStack}-RoleArn"
            Action: 'kms:*'
            Resource: '*'
          - Sid: Enable access by a group of users
            Effect: Allow
            Principal:
              AWS: !Ref AccessPrincipal
            Action: 'kms:*'
            Resource: '*'
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'
          # You may need to add additional permissions here to be able to decrypt the secret
  Clone:
    Type: Custom::AuroraClone
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Sub "${CloneManagerStack}-LambdaArn"
      SourceClusterId: !Ref SourceClusterId
      CopyOk: true
      InstanceClass: db.r4.large
      CopyCreatedSince: !Ref CopyCreatedSince
      SecretKmsKeyId: !Ref SecretKMSKey

Outputs:
  CloneClusterArn:
    Description: The ARN of the created clone
    Value: !GetAtt Clone.Arn
  CloneClusterId:
    Description: The ID of the created clone
    Value: !GetAtt Clone.ClusterId
  CloneClusterEndpoint:
    Description: The endpoint of the created clone
    Value: !GetAtt Clone.Endpoint
  CloneClusterReaderEndpoint:
    Description: The endpoint of the created clone
    Value: !GetAtt Clone.ReaderEndpoint
  ClonePasswordSecret:
    Description: The secret containing the clone password
    Value: !GetAtt Clone.PasswordSecret
