AWSTemplateFormatVersion: '2010-09-09'
Description: 'Aurora clone manager example'
Parameters:
  SourceClusterId:
    Type: String
    Description: "The ID of the root cluster"
  CopyCreatedSince:
    Type: String
    Description: "To be eligible for cloning, a copy must have been created after this time"
    Default: 1970-01-01T00:00:00.000Z
  CloneManagerStack:
    Type: String
    Description: "The name of the stack defining the Aurora clone manager"
    Default: "aurora-clone-manager"
  AccessPrincipalArns:
    Type: CommaDelimitedList
    Description: "The user to grant access to the key, see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#Principal_specifying"
Resources:

  Clone:
    Type: Custom::AuroraClone
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Sub "${CloneManagerStack}-LambdaArn"
      SourceClusterId: !Ref SourceClusterId
      CopyOk: true
      InstanceClass: db.r4.large
      CopyCreatedSince: !Ref CopyCreatedSince
      SetPassword: true
      AccessPrincipalArns: !Ref AccessPrincipalArns

Outputs:
  CloneClusterArn:
    Description: The ARN of the created clone
    Value: !GetAtt Clone.Arn
  CloneClusterId:
    Description: The ID of the created clone
    Value: !GetAtt Clone.ClusterId
  CloneClusterEndpoint:
    Description: The endpoint of the created clone
    Value: !GetAtt Clone.Endpoint
  CloneClusterReaderEndpoint:
    Description: The endpoint of the created clone
    Value: !GetAtt Clone.ReaderEndpoint
  ClonePasswordSecret:
    Description: The secret containing the clone password
    Value: !GetAtt Clone.PasswordSecret
  ClonePasswordKmsKeyId:
    Description: The key used to encrypt the secret
    Value: !GetAtt Clone.KmsKeyId
