version: 0.2

env:
  variables:
    TIMBRE_DEFAULT_STACKTRACE_FONTS: "{}"
phases:
  build:
    commands:
      - bash -c "cd $CODEBUILD_SRC_DIR && GIT_URL=$CODEBUILD_SOURCE_REPO_URL GIT_COMMIT=$(git rev-parse HEAD) $CODEBUILD_SRC_DIR/build.sh"
